/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BambooAuthParamsDTO
 */
public class BambooAuthParamsDTOTest {
    private final BambooAuthParamsDTO model = new BambooAuthParamsDTO();

    /**
     * Model tests for BambooAuthParamsDTO
     */
    @Test
    public void testBambooAuthParamsDTO() {
        // TODO: test BambooAuthParamsDTO
    }

    /**
     * Test the property 'accessKey'
     */
    @Test
    public void accessKeyTest() {
        // TODO: test accessKey
    }

    /**
     * Test the property 'tenantDomainName'
     */
    @Test
    public void tenantDomainNameTest() {
        // TODO: test tenantDomainName
    }

}
