/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BasicS3AuthParamsDTO
 */
public class BasicS3AuthParamsDTOTest {
    private final BasicS3AuthParamsDTO model = new BasicS3AuthParamsDTO();

    /**
     * Model tests for BasicS3AuthParamsDTO
     */
    @Test
    public void testBasicS3AuthParamsDTO() {
        // TODO: test BasicS3AuthParamsDTO
    }

    /**
     * Test the property 'bucketName'
     */
    @Test
    public void bucketNameTest() {
        // TODO: test bucketName
    }

    /**
     * Test the property 'bucketRegion'
     */
    @Test
    public void bucketRegionTest() {
        // TODO: test bucketRegion
    }

    /**
     * Test the property 'accessKey'
     */
    @Test
    public void accessKeyTest() {
        // TODO: test accessKey
    }

    /**
     * Test the property 'secretKey'
     */
    @Test
    public void secretKeyTest() {
        // TODO: test secretKey
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

}
