/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BigQueryServiceAccountParamsDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BigQueryAuthParamsDTO
 */
public class BigQueryAuthParamsDTOTest {
    private final BigQueryAuthParamsDTO model = new BigQueryAuthParamsDTO();

    /**
     * Model tests for BigQueryAuthParamsDTO
     */
    @Test
    public void testBigQueryAuthParamsDTO() {
        // TODO: test BigQueryAuthParamsDTO
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'datasetLocation'
     */
    @Test
    public void datasetLocationTest() {
        // TODO: test datasetLocation
    }

    /**
     * Test the property 'refreshToken'
     */
    @Test
    public void refreshTokenTest() {
        // TODO: test refreshToken
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'clientSecret'
     */
    @Test
    public void clientSecretTest() {
        // TODO: test clientSecret
    }

    /**
     * Test the property 'defaultDataset'
     */
    @Test
    public void defaultDatasetTest() {
        // TODO: test defaultDataset
    }

    /**
     * Test the property 'serviceAccountParams'
     */
    @Test
    public void serviceAccountParamsTest() {
        // TODO: test serviceAccountParams
    }

}
