/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AdpAuthParamsDTO;
import com.konfigthis.client.model.BambooAuthParamsDTO;
import com.konfigthis.client.model.BasicS3AuthParamsDTO;
import com.konfigthis.client.model.BigQueryAuthParamsDTO;
import com.konfigthis.client.model.CopyS3AuthParamsDTO;
import com.konfigthis.client.model.DayforceV2AuthParamsDTO;
import com.konfigthis.client.model.DimensionsAuthParamsDTO;
import com.konfigthis.client.model.FusionAuthParamsDTO;
import com.konfigthis.client.model.GongAuthParamsDTO;
import com.konfigthis.client.model.GoogleSheetsAuthParamsDTO;
import com.konfigthis.client.model.GoogleWorkspaceAuthParamsDTO;
import com.konfigthis.client.model.GreenhouseAuthParamsDTO;
import com.konfigthis.client.model.IcimsAuthParamsDTO;
import com.konfigthis.client.model.InternalS3AuthParamsDTO;
import com.konfigthis.client.model.JdbcAuthParamsDTO;
import com.konfigthis.client.model.JiraAuthParamsDTO;
import com.konfigthis.client.model.LeverAuthParamsDTO;
import com.konfigthis.client.model.MedalliaAuthParamsDTO;
import com.konfigthis.client.model.Microsoft365AuthParamsDTO;
import com.konfigthis.client.model.MySqlAuthParamsDTO;
import com.konfigthis.client.model.NamelyAuthParamsDTO;
import com.konfigthis.client.model.OracleDbAuthParamsDTO;
import com.konfigthis.client.model.QualtricsAuthParamsDTO;
import com.konfigthis.client.model.RedshiftAuthParamsDTO;
import com.konfigthis.client.model.SalesforceAuthParamsDTO;
import com.konfigthis.client.model.SalesforceV2AuthParamsDTO;
import com.konfigthis.client.model.ServiceNowAuthParamsDTO;
import com.konfigthis.client.model.SlackAuthParamsDTO;
import com.konfigthis.client.model.SnowflakeAuthParamsDTO;
import com.konfigthis.client.model.SqlServerAuthParamsDTO;
import com.konfigthis.client.model.SuccessFactorsAuthParamsDTO;
import com.konfigthis.client.model.UltimateAuthParamsDTO;
import com.konfigthis.client.model.WillowAuthParamsDTO;
import com.konfigthis.client.model.WorkdayAuthParamsDTO;
import com.konfigthis.client.model.WorkdayRaasAuthParamsDTO;
import com.konfigthis.client.model.ZoomAuthParamsDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DataProviderAuthParamsDTO
 */
public class DataProviderAuthParamsDTOTest {
    private final DataProviderAuthParamsDTO model = new DataProviderAuthParamsDTO();

    /**
     * Model tests for DataProviderAuthParamsDTO
     */
    @Test
    public void testDataProviderAuthParamsDTO() {
        // TODO: test DataProviderAuthParamsDTO
    }

    /**
     * Test the property 'tenantDomainName'
     */
    @Test
    public void tenantDomainNameTest() {
        // TODO: test tenantDomainName
    }

    /**
     * Test the property 'provider'
     */
    @Test
    public void providerTest() {
        // TODO: test provider
    }

    /**
     * Test the property 'bambooAuthParams'
     */
    @Test
    public void bambooAuthParamsTest() {
        // TODO: test bambooAuthParams
    }

    /**
     * Test the property 'greenhouseAuthParams'
     */
    @Test
    public void greenhouseAuthParamsTest() {
        // TODO: test greenhouseAuthParams
    }

    /**
     * Test the property 'googleSheetsAuthParams'
     */
    @Test
    public void googleSheetsAuthParamsTest() {
        // TODO: test googleSheetsAuthParams
    }

    /**
     * Test the property 'jiraAuthParams'
     */
    @Test
    public void jiraAuthParamsTest() {
        // TODO: test jiraAuthParams
    }

    /**
     * Test the property 'leverAuthParams'
     */
    @Test
    public void leverAuthParamsTest() {
        // TODO: test leverAuthParams
    }

    /**
     * Test the property 'namelyAuthParams'
     */
    @Test
    public void namelyAuthParamsTest() {
        // TODO: test namelyAuthParams
    }

    /**
     * Test the property 'qualtricsAuthParams'
     */
    @Test
    public void qualtricsAuthParamsTest() {
        // TODO: test qualtricsAuthParams
    }

    /**
     * Test the property 'salesforceAuthParams'
     */
    @Test
    public void salesforceAuthParamsTest() {
        // TODO: test salesforceAuthParams
    }

    /**
     * Test the property 'ultimateAuthParams'
     */
    @Test
    public void ultimateAuthParamsTest() {
        // TODO: test ultimateAuthParams
    }

    /**
     * Test the property 'workdayAuthParams'
     */
    @Test
    public void workdayAuthParamsTest() {
        // TODO: test workdayAuthParams
    }

    /**
     * Test the property 'icimsAuthParams'
     */
    @Test
    public void icimsAuthParamsTest() {
        // TODO: test icimsAuthParams
    }

    /**
     * Test the property 'serviceNowAuthParams'
     */
    @Test
    public void serviceNowAuthParamsTest() {
        // TODO: test serviceNowAuthParams
    }

    /**
     * Test the property 'jdbcAuthParams'
     */
    @Test
    public void jdbcAuthParamsTest() {
        // TODO: test jdbcAuthParams
    }

    /**
     * Test the property 's3AuthParams'
     */
    @Test
    public void s3AuthParamsTest() {
        // TODO: test s3AuthParams
    }

    /**
     * Test the property 'internalS3AuthParams'
     */
    @Test
    public void internalS3AuthParamsTest() {
        // TODO: test internalS3AuthParams
    }

    /**
     * Test the property 'copyS3AuthParams'
     */
    @Test
    public void copyS3AuthParamsTest() {
        // TODO: test copyS3AuthParams
    }

    /**
     * Test the property 'redshiftAuthParams'
     */
    @Test
    public void redshiftAuthParamsTest() {
        // TODO: test redshiftAuthParams
    }

    /**
     * Test the property 'snowflakeAuthParams'
     */
    @Test
    public void snowflakeAuthParamsTest() {
        // TODO: test snowflakeAuthParams
    }

    /**
     * Test the property 'bigQueryAuthParams'
     */
    @Test
    public void bigQueryAuthParamsTest() {
        // TODO: test bigQueryAuthParams
    }

    /**
     * Test the property 'sqlServerAuthParams'
     */
    @Test
    public void sqlServerAuthParamsTest() {
        // TODO: test sqlServerAuthParams
    }

    /**
     * Test the property 'dimensionsAuthParams'
     */
    @Test
    public void dimensionsAuthParamsTest() {
        // TODO: test dimensionsAuthParams
    }

    /**
     * Test the property 'willowAuthParams'
     */
    @Test
    public void willowAuthParamsTest() {
        // TODO: test willowAuthParams
    }

    /**
     * Test the property 'emptyAuthParams'
     */
    @Test
    public void emptyAuthParamsTest() {
        // TODO: test emptyAuthParams
    }

    /**
     * Test the property 'successFactorsAuthParams'
     */
    @Test
    public void successFactorsAuthParamsTest() {
        // TODO: test successFactorsAuthParams
    }

    /**
     * Test the property 'fusionAuthParams'
     */
    @Test
    public void fusionAuthParamsTest() {
        // TODO: test fusionAuthParams
    }

    /**
     * Test the property 'adpAuthParams'
     */
    @Test
    public void adpAuthParamsTest() {
        // TODO: test adpAuthParams
    }

    /**
     * Test the property 'medalliaAuthParams'
     */
    @Test
    public void medalliaAuthParamsTest() {
        // TODO: test medalliaAuthParams
    }

    /**
     * Test the property 'salesforceV2AuthParams'
     */
    @Test
    public void salesforceV2AuthParamsTest() {
        // TODO: test salesforceV2AuthParams
    }

    /**
     * Test the property 'gongAuthParams'
     */
    @Test
    public void gongAuthParamsTest() {
        // TODO: test gongAuthParams
    }

    /**
     * Test the property 'zoomAuthParams'
     */
    @Test
    public void zoomAuthParamsTest() {
        // TODO: test zoomAuthParams
    }

    /**
     * Test the property 'dayforceV2AuthParams'
     */
    @Test
    public void dayforceV2AuthParamsTest() {
        // TODO: test dayforceV2AuthParams
    }

    /**
     * Test the property 'slackAuthParams'
     */
    @Test
    public void slackAuthParamsTest() {
        // TODO: test slackAuthParams
    }

    /**
     * Test the property 'mySqlAuthParams'
     */
    @Test
    public void mySqlAuthParamsTest() {
        // TODO: test mySqlAuthParams
    }

    /**
     * Test the property 'workdayRaasAuthParams'
     */
    @Test
    public void workdayRaasAuthParamsTest() {
        // TODO: test workdayRaasAuthParams
    }

    /**
     * Test the property 'ms365AuthParams'
     */
    @Test
    public void ms365AuthParamsTest() {
        // TODO: test ms365AuthParams
    }

    /**
     * Test the property 'googleWorkspaceAuthParams'
     */
    @Test
    public void googleWorkspaceAuthParamsTest() {
        // TODO: test googleWorkspaceAuthParams
    }

    /**
     * Test the property 'oracleDbAuthParams'
     */
    @Test
    public void oracleDbAuthParamsTest() {
        // TODO: test oracleDbAuthParams
    }

    /**
     * Test the property 'hasUpdates'
     */
    @Test
    public void hasUpdatesTest() {
        // TODO: test hasUpdates
    }

    /**
     * Test the property 'authContext'
     */
    @Test
    public void authContextTest() {
        // TODO: test authContext
    }

}
