/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DataProviderAuthParamsDTO;
import com.konfigthis.client.model.DataProviderBasicInformationDTO;
import com.konfigthis.client.model.DataProviderBasicMetadataDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DataProviderAuthInformationDTO
 */
public class DataProviderAuthInformationDTOTest {
    private final DataProviderAuthInformationDTO model = new DataProviderAuthInformationDTO();

    /**
     * Model tests for DataProviderAuthInformationDTO
     */
    @Test
    public void testDataProviderAuthInformationDTO() {
        // TODO: test DataProviderAuthInformationDTO
    }

    /**
     * Test the property 'dataProviderAuthParams'
     */
    @Test
    public void dataProviderAuthParamsTest() {
        // TODO: test dataProviderAuthParams
    }

    /**
     * Test the property 'dataProviderBasicInformation'
     */
    @Test
    public void dataProviderBasicInformationTest() {
        // TODO: test dataProviderBasicInformation
    }

    /**
     * Test the property 'dataProviderMetadata'
     */
    @Test
    public void dataProviderMetadataTest() {
        // TODO: test dataProviderMetadata
    }

}
