/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DayforceV2AuthParamsDTO
 */
public class DayforceV2AuthParamsDTOTest {
    private final DayforceV2AuthParamsDTO model = new DayforceV2AuthParamsDTO();

    /**
     * Model tests for DayforceV2AuthParamsDTO
     */
    @Test
    public void testDayforceV2AuthParamsDTO() {
        // TODO: test DayforceV2AuthParamsDTO
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'tokenHost'
     */
    @Test
    public void tokenHostTest() {
        // TODO: test tokenHost
    }

    /**
     * Test the property 'hostDomainName'
     */
    @Test
    public void hostDomainNameTest() {
        // TODO: test hostDomainName
    }

}
