/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DimensionsAuthParamsDTO
 */
public class DimensionsAuthParamsDTOTest {
    private final DimensionsAuthParamsDTO model = new DimensionsAuthParamsDTO();

    /**
     * Model tests for DimensionsAuthParamsDTO
     */
    @Test
    public void testDimensionsAuthParamsDTO() {
        // TODO: test DimensionsAuthParamsDTO
    }

    /**
     * Test the property 'appKey'
     */
    @Test
    public void appKeyTest() {
        // TODO: test appKey
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'clientSecret'
     */
    @Test
    public void clientSecretTest() {
        // TODO: test clientSecret
    }

    /**
     * Test the property 'vanityUrl'
     */
    @Test
    public void vanityUrlTest() {
        // TODO: test vanityUrl
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

}
