/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExtractorCredentialAPIDTO
 */
public class ExtractorCredentialAPIDTOTest {
    private final ExtractorCredentialAPIDTO model = new ExtractorCredentialAPIDTO();

    /**
     * Model tests for ExtractorCredentialAPIDTO
     */
    @Test
    public void testExtractorCredentialAPIDTO() {
        // TODO: test ExtractorCredentialAPIDTO
    }

    /**
     * Test the property 'credentialId'
     */
    @Test
    public void credentialIdTest() {
        // TODO: test credentialId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'dataProvider'
     */
    @Test
    public void dataProviderTest() {
        // TODO: test dataProvider
    }

    /**
     * Test the property 'isInherited'
     */
    @Test
    public void isInheritedTest() {
        // TODO: test isInherited
    }

    /**
     * Test the property 'authContext'
     */
    @Test
    public void authContextTest() {
        // TODO: test authContext
    }

}
