/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.JiraConnectParamsDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JiraAuthParamsDTO
 */
public class JiraAuthParamsDTOTest {
    private final JiraAuthParamsDTO model = new JiraAuthParamsDTO();

    /**
     * Model tests for JiraAuthParamsDTO
     */
    @Test
    public void testJiraAuthParamsDTO() {
        // TODO: test JiraAuthParamsDTO
    }

    /**
     * Test the property 'apiToken'
     */
    @Test
    public void apiTokenTest() {
        // TODO: test apiToken
    }

    /**
     * Test the property 'hostName'
     */
    @Test
    public void hostNameTest() {
        // TODO: test hostName
    }

    /**
     * Test the property 'connectParams'
     */
    @Test
    public void connectParamsTest() {
        // TODO: test connectParams
    }

}
