/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JiraConnectParamsDTO
 */
public class JiraConnectParamsDTOTest {
    private final JiraConnectParamsDTO model = new JiraConnectParamsDTO();

    /**
     * Model tests for JiraConnectParamsDTO
     */
    @Test
    public void testJiraConnectParamsDTO() {
        // TODO: test JiraConnectParamsDTO
    }

    /**
     * Test the property 'appKey'
     */
    @Test
    public void appKeyTest() {
        // TODO: test appKey
    }

    /**
     * Test the property 'clientKey'
     */
    @Test
    public void clientKeyTest() {
        // TODO: test clientKey
    }

    /**
     * Test the property 'sharedSecret'
     */
    @Test
    public void sharedSecretTest() {
        // TODO: test sharedSecret
    }

}
