/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobCancellationResultDTO
 */
public class JobCancellationResultDTOTest {
    private final JobCancellationResultDTO model = new JobCancellationResultDTO();

    /**
     * Model tests for JobCancellationResultDTO
     */
    @Test
    public void testJobCancellationResultDTO() {
        // TODO: test JobCancellationResultDTO
    }

    /**
     * Test the property 'tenantCode'
     */
    @Test
    public void tenantCodeTest() {
        // TODO: test tenantCode
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    public void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'jobType'
     */
    @Test
    public void jobTypeTest() {
        // TODO: test jobType
    }

    /**
     * Test the property 'parentJobId'
     */
    @Test
    public void parentJobIdTest() {
        // TODO: test parentJobId
    }

    /**
     * Test the property 'cancelStatus'
     */
    @Test
    public void cancelStatusTest() {
        // TODO: test cancelStatus
    }

    /**
     * Test the property 'jobStatus'
     */
    @Test
    public void jobStatusTest() {
        // TODO: test jobStatus
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
