/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MedalliaAuthParamsDTO
 */
public class MedalliaAuthParamsDTOTest {
    private final MedalliaAuthParamsDTO model = new MedalliaAuthParamsDTO();

    /**
     * Model tests for MedalliaAuthParamsDTO
     */
    @Test
    public void testMedalliaAuthParamsDTO() {
        // TODO: test MedalliaAuthParamsDTO
    }

    /**
     * Test the property 'tenantDomainName'
     */
    @Test
    public void tenantDomainNameTest() {
        // TODO: test tenantDomainName
    }

    /**
     * Test the property 'instanceUrl'
     */
    @Test
    public void instanceUrlTest() {
        // TODO: test instanceUrl
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'clientSecret'
     */
    @Test
    public void clientSecretTest() {
        // TODO: test clientSecret
    }

}
