/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Microsoft365AuthParamsDTO
 */
public class Microsoft365AuthParamsDTOTest {
    private final Microsoft365AuthParamsDTO model = new Microsoft365AuthParamsDTO();

    /**
     * Model tests for Microsoft365AuthParamsDTO
     */
    @Test
    public void testMicrosoft365AuthParamsDTO() {
        // TODO: test Microsoft365AuthParamsDTO
    }

    /**
     * Test the property 'oAuthTenantId'
     */
    @Test
    public void oAuthTenantIdTest() {
        // TODO: test oAuthTenantId
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'clientSecret'
     */
    @Test
    public void clientSecretTest() {
        // TODO: test clientSecret
    }

}
