/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DataVersionAndDateDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MultipleTenantDataVersionsDetailsDTO
 */
public class MultipleTenantDataVersionsDetailsDTOTest {
    private final MultipleTenantDataVersionsDetailsDTO model = new MultipleTenantDataVersionsDetailsDTO();

    /**
     * Model tests for MultipleTenantDataVersionsDetailsDTO
     */
    @Test
    public void testMultipleTenantDataVersionsDetailsDTO() {
        // TODO: test MultipleTenantDataVersionsDetailsDTO
    }

    /**
     * Test the property 'tenantCode'
     */
    @Test
    public void tenantCodeTest() {
        // TODO: test tenantCode
    }

    /**
     * Test the property 'dataVersions'
     */
    @Test
    public void dataVersionsTest() {
        // TODO: test dataVersions
    }

}
