/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SnowflakeAuthParamsDTO
 */
public class SnowflakeAuthParamsDTOTest {
    private final SnowflakeAuthParamsDTO model = new SnowflakeAuthParamsDTO();

    /**
     * Model tests for SnowflakeAuthParamsDTO
     */
    @Test
    public void testSnowflakeAuthParamsDTO() {
        // TODO: test SnowflakeAuthParamsDTO
    }

    /**
     * Test the property 'accountIdentifier'
     */
    @Test
    public void accountIdentifierTest() {
        // TODO: test accountIdentifier
    }

    /**
     * Test the property 'database'
     */
    @Test
    public void databaseTest() {
        // TODO: test database
    }

    /**
     * Test the property 'schema'
     */
    @Test
    public void schemaTest() {
        // TODO: test schema
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'warehouse'
     */
    @Test
    public void warehouseTest() {
        // TODO: test warehouse
    }

    /**
     * Test the property 'privateKey'
     */
    @Test
    public void privateKeyTest() {
        // TODO: test privateKey
    }

}
