/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StartExtractionModel
 */
public class StartExtractionModelTest {
    private final StartExtractionModel model = new StartExtractionModel();

    /**
     * Model tests for StartExtractionModel
     */
    @Test
    public void testStartExtractionModel() {
        // TODO: test StartExtractionModel
    }

    /**
     * Test the property 'tenants'
     */
    @Test
    public void tenantsTest() {
        // TODO: test tenants
    }

    /**
     * Test the property 'allTenants'
     */
    @Test
    public void allTenantsTest() {
        // TODO: test allTenants
    }

    /**
     * Test the property 'overrideLastExtractionTimestamp'
     */
    @Test
    public void overrideLastExtractionTimestampTest() {
        // TODO: test overrideLastExtractionTimestamp
    }

    /**
     * Test the property 'publishDataLoadArtifacts'
     */
    @Test
    public void publishDataLoadArtifactsTest() {
        // TODO: test publishDataLoadArtifacts
    }

    /**
     * Test the property 'runProcessingJob'
     */
    @Test
    public void runProcessingJobTest() {
        // TODO: test runProcessingJob
    }

    /**
     * Test the property 'dataCategoryId'
     */
    @Test
    public void dataCategoryIdTest() {
        // TODO: test dataCategoryId
    }

    /**
     * Test the property 'disableArtifactGeneration'
     */
    @Test
    public void disableArtifactGenerationTest() {
        // TODO: test disableArtifactGeneration
    }

}
