/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SuccessFactorsAuthParamsDTO
 */
public class SuccessFactorsAuthParamsDTOTest {
    private final SuccessFactorsAuthParamsDTO model = new SuccessFactorsAuthParamsDTO();

    /**
     * Model tests for SuccessFactorsAuthParamsDTO
     */
    @Test
    public void testSuccessFactorsAuthParamsDTO() {
        // TODO: test SuccessFactorsAuthParamsDTO
    }

    /**
     * Test the property 'hostDomainName'
     */
    @Test
    public void hostDomainNameTest() {
        // TODO: test hostDomainName
    }

    /**
     * Test the property 'companyID'
     */
    @Test
    public void companyIDTest() {
        // TODO: test companyID
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

}
