/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TenantDataUploadUpdateStatusResponseDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TenantDataUploadsUpdateResponseDTO
 */
public class TenantDataUploadsUpdateResponseDTOTest {
    private final TenantDataUploadsUpdateResponseDTO model = new TenantDataUploadsUpdateResponseDTO();

    /**
     * Model tests for TenantDataUploadsUpdateResponseDTO
     */
    @Test
    public void testTenantDataUploadsUpdateResponseDTO() {
        // TODO: test TenantDataUploadsUpdateResponseDTO
    }

    /**
     * Test the property 'totalFailures'
     */
    @Test
    public void totalFailuresTest() {
        // TODO: test totalFailures
    }

    /**
     * Test the property 'totalSuccess'
     */
    @Test
    public void totalSuccessTest() {
        // TODO: test totalSuccess
    }

    /**
     * Test the property 'uploads'
     */
    @Test
    public void uploadsTest() {
        // TODO: test uploads
    }

}
