/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TenantDataUploadStatusResponseDTO
 */
public class TenantDataUploadStatusResponseDTOTest {
    private final TenantDataUploadStatusResponseDTO model = new TenantDataUploadStatusResponseDTO();

    /**
     * Model tests for TenantDataUploadStatusResponseDTO
     */
    @Test
    public void testTenantDataUploadStatusResponseDTO() {
        // TODO: test TenantDataUploadStatusResponseDTO
    }

    /**
     * Test the property 'uploadTime'
     */
    @Test
    public void uploadTimeTest() {
        // TODO: test uploadTime
    }

    /**
     * Test the property 'included'
     */
    @Test
    public void includedTest() {
        // TODO: test included
    }

}
