/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UploadToExclude
 */
public class UploadToExcludeTest {
    private final UploadToExclude model = new UploadToExclude();

    /**
     * Model tests for UploadToExclude
     */
    @Test
    public void testUploadToExclude() {
        // TODO: test UploadToExclude
    }

    /**
     * Test the property 'tenantCode'
     */
    @Test
    public void tenantCodeTest() {
        // TODO: test tenantCode
    }

    /**
     * Test the property 'excludeAll'
     */
    @Test
    public void excludeAllTest() {
        // TODO: test excludeAll
    }

    /**
     * Test the property 'uploadTimes'
     */
    @Test
    public void uploadTimesTest() {
        // TODO: test uploadTimes
    }

}
