/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BigQueryServiceAccountParamsDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * BigQueryAuthParamsDTO
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class BigQueryAuthParamsDTO {
  public static final String SERIALIZED_NAME_PROJECT_ID = "projectId";
  @SerializedName(SERIALIZED_NAME_PROJECT_ID)
  private String projectId;

  public static final String SERIALIZED_NAME_DATASET_LOCATION = "datasetLocation";
  @SerializedName(SERIALIZED_NAME_DATASET_LOCATION)
  private String datasetLocation;

  public static final String SERIALIZED_NAME_REFRESH_TOKEN = "refreshToken";
  @SerializedName(SERIALIZED_NAME_REFRESH_TOKEN)
  private String refreshToken;

  public static final String SERIALIZED_NAME_CLIENT_ID = "clientId";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID)
  private String clientId;

  public static final String SERIALIZED_NAME_CLIENT_SECRET = "clientSecret";
  @SerializedName(SERIALIZED_NAME_CLIENT_SECRET)
  private String clientSecret;

  public static final String SERIALIZED_NAME_DEFAULT_DATASET = "defaultDataset";
  @SerializedName(SERIALIZED_NAME_DEFAULT_DATASET)
  private String defaultDataset;

  public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_PARAMS = "serviceAccountParams";
  @SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_PARAMS)
  private BigQueryServiceAccountParamsDTO serviceAccountParams;

  public BigQueryAuthParamsDTO() {
  }

  public BigQueryAuthParamsDTO projectId(String projectId) {
    
    
    
    
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProjectId() {
    return projectId;
  }


  public void setProjectId(String projectId) {
    
    
    
    this.projectId = projectId;
  }


  public BigQueryAuthParamsDTO datasetLocation(String datasetLocation) {
    
    
    
    
    this.datasetLocation = datasetLocation;
    return this;
  }

   /**
   * Get datasetLocation
   * @return datasetLocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDatasetLocation() {
    return datasetLocation;
  }


  public void setDatasetLocation(String datasetLocation) {
    
    
    
    this.datasetLocation = datasetLocation;
  }


  public BigQueryAuthParamsDTO refreshToken(String refreshToken) {
    
    
    
    
    this.refreshToken = refreshToken;
    return this;
  }

   /**
   * Get refreshToken
   * @return refreshToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRefreshToken() {
    return refreshToken;
  }


  public void setRefreshToken(String refreshToken) {
    
    
    
    this.refreshToken = refreshToken;
  }


  public BigQueryAuthParamsDTO clientId(String clientId) {
    
    
    
    
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClientId() {
    return clientId;
  }


  public void setClientId(String clientId) {
    
    
    
    this.clientId = clientId;
  }


  public BigQueryAuthParamsDTO clientSecret(String clientSecret) {
    
    
    
    
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * Get clientSecret
   * @return clientSecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClientSecret() {
    return clientSecret;
  }


  public void setClientSecret(String clientSecret) {
    
    
    
    this.clientSecret = clientSecret;
  }


  public BigQueryAuthParamsDTO defaultDataset(String defaultDataset) {
    
    
    
    
    this.defaultDataset = defaultDataset;
    return this;
  }

   /**
   * Get defaultDataset
   * @return defaultDataset
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDefaultDataset() {
    return defaultDataset;
  }


  public void setDefaultDataset(String defaultDataset) {
    
    
    
    this.defaultDataset = defaultDataset;
  }


  public BigQueryAuthParamsDTO serviceAccountParams(BigQueryServiceAccountParamsDTO serviceAccountParams) {
    
    
    
    
    this.serviceAccountParams = serviceAccountParams;
    return this;
  }

   /**
   * Get serviceAccountParams
   * @return serviceAccountParams
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigQueryServiceAccountParamsDTO getServiceAccountParams() {
    return serviceAccountParams;
  }


  public void setServiceAccountParams(BigQueryServiceAccountParamsDTO serviceAccountParams) {
    
    
    
    this.serviceAccountParams = serviceAccountParams;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the BigQueryAuthParamsDTO instance itself
   */
  public BigQueryAuthParamsDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BigQueryAuthParamsDTO bigQueryAuthParamsDTO = (BigQueryAuthParamsDTO) o;
    return Objects.equals(this.projectId, bigQueryAuthParamsDTO.projectId) &&
        Objects.equals(this.datasetLocation, bigQueryAuthParamsDTO.datasetLocation) &&
        Objects.equals(this.refreshToken, bigQueryAuthParamsDTO.refreshToken) &&
        Objects.equals(this.clientId, bigQueryAuthParamsDTO.clientId) &&
        Objects.equals(this.clientSecret, bigQueryAuthParamsDTO.clientSecret) &&
        Objects.equals(this.defaultDataset, bigQueryAuthParamsDTO.defaultDataset) &&
        Objects.equals(this.serviceAccountParams, bigQueryAuthParamsDTO.serviceAccountParams)&&
        Objects.equals(this.additionalProperties, bigQueryAuthParamsDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, datasetLocation, refreshToken, clientId, clientSecret, defaultDataset, serviceAccountParams, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BigQueryAuthParamsDTO {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    datasetLocation: ").append(toIndentedString(datasetLocation)).append("\n");
    sb.append("    refreshToken: ").append(toIndentedString(refreshToken)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    defaultDataset: ").append(toIndentedString(defaultDataset)).append("\n");
    sb.append("    serviceAccountParams: ").append(toIndentedString(serviceAccountParams)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("projectId");
    openapiFields.add("datasetLocation");
    openapiFields.add("refreshToken");
    openapiFields.add("clientId");
    openapiFields.add("clientSecret");
    openapiFields.add("defaultDataset");
    openapiFields.add("serviceAccountParams");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BigQueryAuthParamsDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!BigQueryAuthParamsDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BigQueryAuthParamsDTO is not found in the empty JSON string", BigQueryAuthParamsDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("projectId") != null && !jsonObj.get("projectId").isJsonNull()) && !jsonObj.get("projectId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `projectId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("projectId").toString()));
      }
      if ((jsonObj.get("datasetLocation") != null && !jsonObj.get("datasetLocation").isJsonNull()) && !jsonObj.get("datasetLocation").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `datasetLocation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("datasetLocation").toString()));
      }
      if ((jsonObj.get("refreshToken") != null && !jsonObj.get("refreshToken").isJsonNull()) && !jsonObj.get("refreshToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `refreshToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("refreshToken").toString()));
      }
      if ((jsonObj.get("clientId") != null && !jsonObj.get("clientId").isJsonNull()) && !jsonObj.get("clientId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clientId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clientId").toString()));
      }
      if ((jsonObj.get("clientSecret") != null && !jsonObj.get("clientSecret").isJsonNull()) && !jsonObj.get("clientSecret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clientSecret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clientSecret").toString()));
      }
      if ((jsonObj.get("defaultDataset") != null && !jsonObj.get("defaultDataset").isJsonNull()) && !jsonObj.get("defaultDataset").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `defaultDataset` to be a primitive type in the JSON string but got `%s`", jsonObj.get("defaultDataset").toString()));
      }
      // validate the optional field `serviceAccountParams`
      if (jsonObj.get("serviceAccountParams") != null && !jsonObj.get("serviceAccountParams").isJsonNull()) {
        BigQueryServiceAccountParamsDTO.validateJsonObject(jsonObj.getAsJsonObject("serviceAccountParams"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BigQueryAuthParamsDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BigQueryAuthParamsDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BigQueryAuthParamsDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BigQueryAuthParamsDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<BigQueryAuthParamsDTO>() {
           @Override
           public void write(JsonWriter out, BigQueryAuthParamsDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public BigQueryAuthParamsDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             BigQueryAuthParamsDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BigQueryAuthParamsDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BigQueryAuthParamsDTO
  * @throws IOException if the JSON string is invalid with respect to BigQueryAuthParamsDTO
  */
  public static BigQueryAuthParamsDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BigQueryAuthParamsDTO.class);
  }

 /**
  * Convert an instance of BigQueryAuthParamsDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

