/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SubjectMissingAccessDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * CredentialCreationAPIResponseDTO
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CredentialCreationAPIResponseDTO {
  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_SYMBOL_NAME = "symbolName";
  @SerializedName(SERIALIZED_NAME_SYMBOL_NAME)
  private String symbolName;

  public static final String SERIALIZED_NAME_OBJECT_NAME = "objectName";
  @SerializedName(SERIALIZED_NAME_OBJECT_NAME)
  private String objectName;

  public static final String SERIALIZED_NAME_MISSING_CONNECTION_PROPERTIES = "missingConnectionProperties";
  @SerializedName(SERIALIZED_NAME_MISSING_CONNECTION_PROPERTIES)
  private List<SubjectMissingAccessDTO> missingConnectionProperties = null;

  public CredentialCreationAPIResponseDTO() {
  }

  public CredentialCreationAPIResponseDTO uuid(String uuid) {
    
    
    
    
    this.uuid = uuid;
    return this;
  }

   /**
   * The unique ID of the newly created credential.
   * @return uuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique ID of the newly created credential.")

  public String getUuid() {
    return uuid;
  }


  public void setUuid(String uuid) {
    
    
    
    this.uuid = uuid;
  }


  public CredentialCreationAPIResponseDTO symbolName(String symbolName) {
    
    
    
    
    this.symbolName = symbolName;
    return this;
  }

   /**
   * The symbol name of the newly created credential.
   * @return symbolName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The symbol name of the newly created credential.")

  public String getSymbolName() {
    return symbolName;
  }


  public void setSymbolName(String symbolName) {
    
    
    
    this.symbolName = symbolName;
  }


  public CredentialCreationAPIResponseDTO objectName(String objectName) {
    
    
    
    
    this.objectName = objectName;
    return this;
  }

   /**
   * The object name of the newly created credential.
   * @return objectName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The object name of the newly created credential.")

  public String getObjectName() {
    return objectName;
  }


  public void setObjectName(String objectName) {
    
    
    
    this.objectName = objectName;
  }


  public CredentialCreationAPIResponseDTO missingConnectionProperties(List<SubjectMissingAccessDTO> missingConnectionProperties) {
    
    
    
    
    this.missingConnectionProperties = missingConnectionProperties;
    return this;
  }

  public CredentialCreationAPIResponseDTO addMissingConnectionPropertiesItem(SubjectMissingAccessDTO missingConnectionPropertiesItem) {
    if (this.missingConnectionProperties == null) {
      this.missingConnectionProperties = new ArrayList<>();
    }
    this.missingConnectionProperties.add(missingConnectionPropertiesItem);
    return this;
  }

   /**
   * The properties that the credential cannot access despite successful authentication.  This is only returned for authentications that do not grant access to all data.
   * @return missingConnectionProperties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The properties that the credential cannot access despite successful authentication.  This is only returned for authentications that do not grant access to all data.")

  public List<SubjectMissingAccessDTO> getMissingConnectionProperties() {
    return missingConnectionProperties;
  }


  public void setMissingConnectionProperties(List<SubjectMissingAccessDTO> missingConnectionProperties) {
    
    
    
    this.missingConnectionProperties = missingConnectionProperties;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CredentialCreationAPIResponseDTO instance itself
   */
  public CredentialCreationAPIResponseDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CredentialCreationAPIResponseDTO credentialCreationAPIResponseDTO = (CredentialCreationAPIResponseDTO) o;
    return Objects.equals(this.uuid, credentialCreationAPIResponseDTO.uuid) &&
        Objects.equals(this.symbolName, credentialCreationAPIResponseDTO.symbolName) &&
        Objects.equals(this.objectName, credentialCreationAPIResponseDTO.objectName) &&
        Objects.equals(this.missingConnectionProperties, credentialCreationAPIResponseDTO.missingConnectionProperties)&&
        Objects.equals(this.additionalProperties, credentialCreationAPIResponseDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, symbolName, objectName, missingConnectionProperties, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CredentialCreationAPIResponseDTO {\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    symbolName: ").append(toIndentedString(symbolName)).append("\n");
    sb.append("    objectName: ").append(toIndentedString(objectName)).append("\n");
    sb.append("    missingConnectionProperties: ").append(toIndentedString(missingConnectionProperties)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("uuid");
    openapiFields.add("symbolName");
    openapiFields.add("objectName");
    openapiFields.add("missingConnectionProperties");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CredentialCreationAPIResponseDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CredentialCreationAPIResponseDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CredentialCreationAPIResponseDTO is not found in the empty JSON string", CredentialCreationAPIResponseDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("uuid") != null && !jsonObj.get("uuid").isJsonNull()) && !jsonObj.get("uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uuid").toString()));
      }
      if ((jsonObj.get("symbolName") != null && !jsonObj.get("symbolName").isJsonNull()) && !jsonObj.get("symbolName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `symbolName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("symbolName").toString()));
      }
      if ((jsonObj.get("objectName") != null && !jsonObj.get("objectName").isJsonNull()) && !jsonObj.get("objectName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `objectName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("objectName").toString()));
      }
      if (jsonObj.get("missingConnectionProperties") != null && !jsonObj.get("missingConnectionProperties").isJsonNull()) {
        JsonArray jsonArraymissingConnectionProperties = jsonObj.getAsJsonArray("missingConnectionProperties");
        if (jsonArraymissingConnectionProperties != null) {
          // ensure the json data is an array
          if (!jsonObj.get("missingConnectionProperties").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `missingConnectionProperties` to be an array in the JSON string but got `%s`", jsonObj.get("missingConnectionProperties").toString()));
          }

          // validate the optional field `missingConnectionProperties` (array)
          for (int i = 0; i < jsonArraymissingConnectionProperties.size(); i++) {
            SubjectMissingAccessDTO.validateJsonObject(jsonArraymissingConnectionProperties.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CredentialCreationAPIResponseDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CredentialCreationAPIResponseDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CredentialCreationAPIResponseDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CredentialCreationAPIResponseDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<CredentialCreationAPIResponseDTO>() {
           @Override
           public void write(JsonWriter out, CredentialCreationAPIResponseDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CredentialCreationAPIResponseDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CredentialCreationAPIResponseDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CredentialCreationAPIResponseDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CredentialCreationAPIResponseDTO
  * @throws IOException if the JSON string is invalid with respect to CredentialCreationAPIResponseDTO
  */
  public static CredentialCreationAPIResponseDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CredentialCreationAPIResponseDTO.class);
  }

 /**
  * Convert an instance of CredentialCreationAPIResponseDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

