/*
 * Visier Data and Job Handling APIs
 * Visier APIs for data and job handling
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * UploadToInclude
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class UploadToInclude {
  public static final String SERIALIZED_NAME_TENANT_CODE = "tenantCode";
  @SerializedName(SERIALIZED_NAME_TENANT_CODE)
  private String tenantCode;

  public static final String SERIALIZED_NAME_INCLUDE_ALL = "includeAll";
  @SerializedName(SERIALIZED_NAME_INCLUDE_ALL)
  private Boolean includeAll;

  public static final String SERIALIZED_NAME_UPLOAD_TIMES = "uploadTimes";
  @SerializedName(SERIALIZED_NAME_UPLOAD_TIMES)
  private List<String> uploadTimes = null;

  public UploadToInclude() {
  }

  public UploadToInclude tenantCode(String tenantCode) {
    
    
    
    
    this.tenantCode = tenantCode;
    return this;
  }

   /**
   * The tenant code of the analytic tenant you are including a data upload for.
   * @return tenantCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The tenant code of the analytic tenant you are including a data upload for.")

  public String getTenantCode() {
    return tenantCode;
  }


  public void setTenantCode(String tenantCode) {
    
    
    
    this.tenantCode = tenantCode;
  }


  public UploadToInclude includeAll(Boolean includeAll) {
    
    
    
    
    this.includeAll = includeAll;
    return this;
  }

   /**
   * If \&quot;true\&quot;, all data uploads are included for the analytic tenant.
   * @return includeAll
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If \"true\", all data uploads are included for the analytic tenant.")

  public Boolean getIncludeAll() {
    return includeAll;
  }


  public void setIncludeAll(Boolean includeAll) {
    
    
    
    this.includeAll = includeAll;
  }


  public UploadToInclude uploadTimes(List<String> uploadTimes) {
    
    
    
    
    this.uploadTimes = uploadTimes;
    return this;
  }

  public UploadToInclude addUploadTimesItem(String uploadTimesItem) {
    if (this.uploadTimes == null) {
      this.uploadTimes = new ArrayList<>();
    }
    this.uploadTimes.add(uploadTimesItem);
    return this;
  }

   /**
   * A comma-separated list of strings representing the upload time of each data upload to include.
   * @return uploadTimes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A comma-separated list of strings representing the upload time of each data upload to include.")

  public List<String> getUploadTimes() {
    return uploadTimes;
  }


  public void setUploadTimes(List<String> uploadTimes) {
    
    
    
    this.uploadTimes = uploadTimes;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UploadToInclude instance itself
   */
  public UploadToInclude putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UploadToInclude uploadToInclude = (UploadToInclude) o;
    return Objects.equals(this.tenantCode, uploadToInclude.tenantCode) &&
        Objects.equals(this.includeAll, uploadToInclude.includeAll) &&
        Objects.equals(this.uploadTimes, uploadToInclude.uploadTimes)&&
        Objects.equals(this.additionalProperties, uploadToInclude.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantCode, includeAll, uploadTimes, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UploadToInclude {\n");
    sb.append("    tenantCode: ").append(toIndentedString(tenantCode)).append("\n");
    sb.append("    includeAll: ").append(toIndentedString(includeAll)).append("\n");
    sb.append("    uploadTimes: ").append(toIndentedString(uploadTimes)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tenantCode");
    openapiFields.add("includeAll");
    openapiFields.add("uploadTimes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UploadToInclude
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!UploadToInclude.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UploadToInclude is not found in the empty JSON string", UploadToInclude.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("tenantCode") != null && !jsonObj.get("tenantCode").isJsonNull()) && !jsonObj.get("tenantCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantCode").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("uploadTimes") != null && !jsonObj.get("uploadTimes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `uploadTimes` to be an array in the JSON string but got `%s`", jsonObj.get("uploadTimes").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UploadToInclude.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UploadToInclude' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UploadToInclude> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UploadToInclude.class));

       return (TypeAdapter<T>) new TypeAdapter<UploadToInclude>() {
           @Override
           public void write(JsonWriter out, UploadToInclude value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UploadToInclude read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             UploadToInclude instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UploadToInclude given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UploadToInclude
  * @throws IOException if the JSON string is invalid with respect to UploadToInclude
  */
  public static UploadToInclude fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UploadToInclude.class);
  }

 /**
  * Convert an instance of UploadToInclude to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

